# Generated by Django 5.1 on 2024-08-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("requires_race", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("password_hash", models.CharField(max_length=120)),
                ("password_salt", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Mod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("short_desc", models.TextField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="mods/")),
                ("file_size", models.CharField(max_length=20)),
                ("downloads", models.IntegerField(default=0)),
                ("categories", models.ManyToManyField(related_name="mods", to="mods.category")),
                ("races", models.ManyToManyField(blank=True, related_name="mods", to="mods.race")),
                ("tags", models.ManyToManyField(blank=True, related_name="mods", to="mods.tag")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mods.user")),
            ],
        ),
        migrations.CreateModel(
            name="ModImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="mod_images/")),
                ("mod", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mods.mod")),
            ],
        ),
    ]
