# Generated by Django 5.1 on 2024-08-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
