# Generated by Django 5.1 on 2024-08-15 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mods", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="mod",
            name="races",
        ),
        migrations.AddField(
            model_name="mod",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mod",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="modimage",
            name="is_thumbnail",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mod",
            name="file_size",
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name="ModCompatibility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="mods.gender"
                    ),
                ),
                ("mod", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mods.mod")),
                ("race", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mods.race")),
            ],
        ),
    ]
