name: Linting and Formatting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install flake8 isort black

      - name: Run isort (Import Sorting)
        run: |
          . venv/bin/activate
          isort .

      - name: Run black (Code Formatting)
        run: |
          . venv/bin/activate
          black .

      - name: Run flake8 (Linting)
        run: |
          . venv/bin/activate
          flake8 .
